#!/bin/bash

mkdir ./output

python3 ./backend/latex2json.py ./input/phy.tex
python3 ./backend/latex2json.py ./input/chem.tex
python3 ./backend/latex2json.py ./input/math.tex

python3 ./backend/combine_json.py

rm -rf ./output/
